#include "Processor.h"
#include <juce_gui_extra/juce_gui_extra.h>
namespace {
const juce::Colour ink(0xff302b42), muted(0xff898395), line(0xffe5e0eb), paper(0xfffcfbfe);
const juce::Colour colours[8]={juce::Colour(0xffe878a2),juce::Colour(0xffee9678),juce::Colour(0xffcfaa4e),juce::Colour(0xff6abda5),juce::Colour(0xff75aada),juce::Colour(0xffaa88d2),juce::Colour(0xff87ad6c),juce::Colour(0xffb48fce)};
struct Style:juce::LookAndFeel_V4 {
 Style(){setColour(juce::TextButton::buttonColourId,juce::Colour(0xffeee8f5));setColour(juce::TextButton::textColourOffId,ink);setColour(juce::TextButton::buttonOnColourId,juce::Colour(0xffd9c8f2));setColour(juce::TextButton::textColourOnId,ink);setColour(juce::ComboBox::backgroundColourId,paper);setColour(juce::ComboBox::textColourId,ink);setColour(juce::ComboBox::outlineColourId,line);setColour(juce::PopupMenu::backgroundColourId,paper);setColour(juce::PopupMenu::textColourId,ink);setColour(juce::TextEditor::backgroundColourId,paper);setColour(juce::TextEditor::textColourId,ink);setColour(juce::TextEditor::outlineColourId,line);setColour(juce::Slider::thumbColourId,juce::Colour(0xffaf94cd));setColour(juce::Slider::trackColourId,juce::Colour(0xffcbb7e1));setColour(juce::Slider::backgroundColourId,line);setColour(juce::Slider::textBoxTextColourId,ink);setColour(juce::Label::textColourId,ink);setColour(juce::Label::textWhenEditingColourId,ink);setColour(juce::Slider::textBoxOutlineColourId,juce::Colours::transparentBlack);setColour(juce::ToggleButton::textColourId,ink);setColour(juce::ToggleButton::tickColourId,juce::Colour(0xff9273b8));}
 void drawButtonBackground(juce::Graphics& g,juce::Button& b,const juce::Colour& c,bool over,bool down) override {g.setColour(c.withMultipliedBrightness(down?0.92f:over?0.97f:1.f));g.fillRoundedRectangle(b.getLocalBounds().toFloat().reduced(0.5f),7);}
};
class Editor final:public juce::AudioProcessorEditor,private juce::Timer,public juce::DragAndDropContainer {
 LatticeProcessor& p;Style style;
 juce::TextButton play{"PLAY"},generate{"GENERATE / 16 BARS"},reroll{"NEW SEED"},exportButton{"DRAG MIDI"},saveButton{"SAVE .MID"},addGroup{"+ GROUP"};
 std::array<juce::TextButton,16> bars16;
 std::array<juce::TextButton,8> locks;
 juce::TextButton divide3{"/ 3"},divide6{"/ 6"},restore{"1/16"},off{"OFF"};
 juce::TextButton grid16{"1/16"},grid32{"1/32"};
 juce::ToggleButton barLock{"Bar lock"};
 juce::TextButton variate{"VARIATE BAR"},copyBar{"COPY > NEXT"};
 juce::ComboBox meter;juce::TextEditor numerator,groupEdit,seedEdit;juce::ComboBox denominator;
 juce::Slider density,tempo,development,fill,space;juce::ToggleButton ghost{"Ghost notes"},accent{"Group accents"};
 std::unique_ptr<juce::FileChooser> chooser;
 int bar=0,selectedRow=-1,anchor=-1,endCell=-1; bool dragging=false;juce::Point<int> down;
 juce::String status="Ready. Set a meter and grouping, then generate 16 bars.";
 juce::Rectangle<int> grid{150,190,690,336};
 struct ExportDrag:juce::MouseListener {Editor& e;bool done=false;ExportDrag(Editor& x):e(x){}void mouseDown(const juce::MouseEvent&)override{done=false;}void mouseDrag(const juce::MouseEvent& ev)override{if(!done&&ev.getDistanceFromDragStart()>5){done=true;auto f=e.p.exportMidi();if(f.existsAsFile())juce::DragAndDropContainer::performExternalDragDropOfFiles({f.getFullPathName()},false,&e);else e.status="MIDI export failed.";}}} dragListener{*this};
 void text(juce::Graphics& g,juce::String s,juce::Rectangle<int> r,float size=13,juce::Colour c=ink,int flags=juce::Justification::centredLeft){g.setColour(c);g.setFont(size);g.drawText(s,r,flags);}
 void commit(){p.changed();repaint();}
 void clearSelection(){selectedRow=anchor=endCell=-1;updateSelection();}
 void updateSelection(){bool on=selectedRow>=0&&anchor>=0&&endCell>=0;for(auto* b:{&divide3,&divide6,&restore,&off})b->setVisible(on);repaint();}
 void subdivision(int n){if(selectedRow<0)return;{juce::ScopedLock lock(p.modelLock);bool ok=p.pattern.subdivide(bar,selectedRow,std::min(anchor,endCell),std::max(anchor,endCell),n);status=ok?"Timing preserved. Click notes to edit velocities.":"Subdivision refused: incompatible duration or existing off-grid notes. Clear those notes first.";}clearSelection();commit();}
 std::pair<int,int> snapHit(juce::Point<int> pt){auto h=hit(pt);if(h.first<0)return h;juce::ScopedLock lock(p.modelLock);auto& lane=p.pattern.bars[bar][h.first];int t=int(double(pt.x-grid.getX())/grid.getWidth()*p.pattern.barTicks());auto cell=lane[h.second];if(cell.start%60!=0||cell.length%60!=0)return h;int step=p.pattern.gridStep;int snap=(t/step)*step;if(cell.velocity&&cell.length==60)return h;for(int i=0;i<int(lane.size());++i)if(snap>=lane[i].start&&snap<lane[i].start+lane[i].length){auto c=lane[i];if(c.length>step&&c.start%step==0&&c.length%step==0){int count=c.length/step;lane.erase(lane.begin()+i);for(int k=0;k<count;++k)lane.insert(lane.begin()+i+k,{c.start+k*step,step,k==0?c.velocity:0});return{h.first,i+(snap-c.start)/step};}return{h.first,i};}return h;}
 void setMeter(){if(meter.getSelectedId()==4){numerator.setVisible(true);denominator.setVisible(true);return;}int n=meter.getSelectedId()==2?7:meter.getSelectedId()==3?5:4;int d=meter.getSelectedId()==2?8:4;applyMeter(n,d);numerator.setVisible(false);denominator.setVisible(false);}
 void applyMeter(int n,int d){juce::ScopedLock lock(p.modelLock);if(p.pattern.numerator==n&&p.pattern.denominator==d)return;p.pattern.meter(n,d);for(auto& b:locks)b.setToggleState(false,juce::dontSendNotification);barLock.setToggleState(false,juce::dontSendNotification);for(auto& b:bars16)b.setToggleState(false,juce::dontSendNotification);groupEdit.setText(juce::String(p.pattern.eighths()),false);status="Meter changed: pattern cleared, locks reset. Choose grouping.";clearSelection();commit();}
 void parseGroups(){auto strings=juce::StringArray::fromTokens(groupEdit.getText(),"+ ,","");std::vector<int> gs;for(auto& s:strings){if(s.containsOnly("0123456789")&&s.getIntValue()>0&&s.getIntValue()<=32)gs.push_back(s.getIntValue());else{status="Grouping must contain positive whole numbers.";repaint();return;}}{juce::ScopedLock lock(p.modelLock);p.pattern.groups=gs;status=p.pattern.valid()?"Grouping valid. Ready to generate.":"Grouping total must match the bar in eighth notes.";}commit();}
 void sync(){juce::ScopedLock lock(p.modelLock);auto& m=p.pattern;tempo.setValue(m.bpm,juce::dontSendNotification);density.setValue(m.density,juce::dontSendNotification);development.setValue(m.development,juce::dontSendNotification);fill.setValue(m.fill,juce::dontSendNotification);space.setValue(m.space,juce::dontSendNotification);ghost.setToggleState(m.ghost,juce::dontSendNotification);accent.setToggleState(m.accents,juce::dontSendNotification);seedEdit.setText(juce::String(m.seed),false);juce::StringArray a;for(int n:m.groups)a.add(juce::String(n));groupEdit.setText(a.joinIntoString("+"),false);int id=m.numerator==4&&m.denominator==4?1:m.numerator==7&&m.denominator==8?2:m.numerator==5&&m.denominator==4?3:4;meter.setSelectedId(id,juce::dontSendNotification);numerator.setText(juce::String(m.numerator),false);denominator.setSelectedId(m.denominator,juce::dontSendNotification);numerator.setVisible(id==4);denominator.setVisible(id==4);for(int r=0;r<8;++r)locks[r].setToggleState(m.locked[r],juce::dontSendNotification);for(int b=0;b<16;++b)bars16[b].setToggleState(b==bar,juce::dontSendNotification);barLock.setToggleState(m.barLocked[bar],juce::dontSendNotification);barLock.setButtonText("LOCK BAR "+juce::String(bar+1));grid16.setToggleState(m.gridStep==120,juce::dontSendNotification);grid32.setToggleState(m.gridStep==60,juce::dontSendNotification);}
 void timerCallback()override{play.setButtonText(p.preview.load()?"STOP":"PLAY");if(!isMouseButtonDownAnywhere()&&!groupEdit.hasKeyboardFocus(true)&&!seedEdit.hasKeyboardFocus(true)&&!numerator.hasKeyboardFocus(true)&&!tempo.isMouseOverOrDragging()&&!density.isMouseOverOrDragging()&&!development.isMouseOverOrDragging()&&!fill.isMouseOverOrDragging()&&!space.isMouseOverOrDragging())sync();repaint();}
 std::pair<int,int> hit(juce::Point<int> pt){if(!grid.contains(pt))return{-1,-1};int r=(pt.y-grid.getY())/42;if(r<0||r>=8)return{-1,-1};juce::ScopedLock lock(p.modelLock);auto& l=p.pattern.bars[bar][r];double t=double(pt.x-grid.getX())/grid.getWidth()*p.pattern.barTicks();for(int i=0;i<int(l.size());++i)if(t>=l[i].start&&t<l[i].start+l[i].length)return{r,i};return{-1,-1};}
public:
 Editor(LatticeProcessor& proc):AudioProcessorEditor(proc),p(proc){setLookAndFeel(&style);setOpaque(true);
 for(auto* b:{&play,&generate,&reroll,&exportButton,&saveButton,&addGroup,&divide3,&divide6,&restore,&off,&grid16,&grid32,&variate,&copyBar})addAndMakeVisible(*b);
 addAndMakeVisible(barLock);addAndMakeVisible(ghost);addAndMakeVisible(accent);
 for(int i=0;i<16;++i){auto& b=bars16[i];b.setButtonText(juce::String(i+1));b.setClickingTogglesState(false);b.onClick=[this,i]{bar=i;clearSelection();repaint();};addAndMakeVisible(b);}
 for(int r=0;r<8;++r){auto& b=locks[r];b.setButtonText("L");b.setClickingTogglesState(true);b.setTooltip("Lock this track across all bars during generation");b.onClick=[this,r]{juce::ScopedLock lock(p.modelLock);p.pattern.locked[r]=locks[r].getToggleState();commit();};addAndMakeVisible(b);}
 meter.addItem("4 / 4",1);meter.addItem("7 / 8",2);meter.addItem("5 / 4",3);meter.addItem("CUSTOM",4);meter.onChange=[this]{setMeter();};addAndMakeVisible(meter);
 denominator.addItem("/ 4",4);denominator.addItem("/ 8",8);denominator.onChange=[this]{applyMeter(std::clamp(numerator.getText().getIntValue(),1,16),denominator.getSelectedId());};addAndMakeVisible(denominator);
 numerator.setInputRestrictions(2,"0123456789");numerator.onReturnKey=[this]{applyMeter(std::clamp(numerator.getText().getIntValue(),1,16),denominator.getSelectedId());};numerator.onFocusLost=numerator.onReturnKey;addAndMakeVisible(numerator);
 groupEdit.setInputRestrictions(80,"0123456789+ ,");groupEdit.onReturnKey=[this]{parseGroups();};groupEdit.onFocusLost=groupEdit.onReturnKey;addAndMakeVisible(groupEdit);
 seedEdit.setInputRestrictions(9,"0123456789");seedEdit.onFocusLost=[this]{juce::ScopedLock lock(p.modelLock);p.pattern.seed=seedEdit.getText().getIntValue();};seedEdit.onReturnKey=seedEdit.onFocusLost;addAndMakeVisible(seedEdit);
 density.setRange(0,1,0.01);density.setSliderStyle(juce::Slider::LinearHorizontal);density.setTextBoxStyle(juce::Slider::TextBoxRight,false,40,20);density.onValueChange=[this]{juce::ScopedLock lock(p.modelLock);p.pattern.density=float(density.getValue());};addAndMakeVisible(density);
 development.setRange(0,1,0.01);development.setSliderStyle(juce::Slider::LinearHorizontal);development.setTextBoxStyle(juce::Slider::TextBoxRight,false,40,20);development.onValueChange=[this]{juce::ScopedLock lock(p.modelLock);p.pattern.development=float(development.getValue());};addAndMakeVisible(development);
 fill.setRange(0,1,0.01);fill.setSliderStyle(juce::Slider::LinearHorizontal);fill.setTextBoxStyle(juce::Slider::TextBoxRight,false,40,20);fill.onValueChange=[this]{juce::ScopedLock lock(p.modelLock);p.pattern.fill=float(fill.getValue());};addAndMakeVisible(fill);
 space.setRange(0,1,0.01);space.setSliderStyle(juce::Slider::LinearHorizontal);space.setTextBoxStyle(juce::Slider::TextBoxRight,false,40,20);space.onValueChange=[this]{juce::ScopedLock lock(p.modelLock);p.pattern.space=float(space.getValue());};addAndMakeVisible(space);
 tempo.setRange(40,240,1);tempo.setSliderStyle(juce::Slider::LinearHorizontal);tempo.setTextBoxStyle(juce::Slider::TextBoxRight,false,42,20);tempo.onValueChange=[this]{juce::ScopedLock lock(p.modelLock);p.pattern.bpm=tempo.getValue();commit();};addAndMakeVisible(tempo);
 ghost.onClick=[this]{juce::ScopedLock lock(p.modelLock);p.pattern.ghost=ghost.getToggleState();};accent.onClick=[this]{juce::ScopedLock lock(p.modelLock);p.pattern.accents=accent.getToggleState();};addAndMakeVisible(ghost);addAndMakeVisible(accent);
 barLock.setClickingTogglesState(true);barLock.onClick=[this]{juce::ScopedLock lock(p.modelLock);p.pattern.barLocked[bar]=barLock.getToggleState();commit();};
 grid16.setClickingTogglesState(true);grid16.onClick=[this]{juce::ScopedLock lock(p.modelLock);p.pattern.gridStep=120;repaint();};
 grid32.setClickingTogglesState(true);grid32.onClick=[this]{juce::ScopedLock lock(p.modelLock);p.pattern.gridStep=60;repaint();};
 play.onClick=[this]{p.preview.store(!p.preview.load());};generate.onClick=[this]{parseGroups();juce::ScopedLock lock(p.modelLock);p.pattern.seed=seedEdit.getText().getIntValue();auto backup=p.pattern.bars;bool ok=p.pattern.generate();if(ok){for(int b=0;b<16;++b)if(p.pattern.barLocked[b])p.pattern.bars[b]=backup[b];status="Generated 16 bars. Locked tracks & bars preserved.";}else status="Fix grouping before generating.";clearSelection();commit();};reroll.onClick=[this]{seedEdit.setText(juce::String(juce::Random::getSystemRandom().nextInt(999999999)),false);generate.triggerClick();};
 addGroup.onClick=[this]{groupEdit.setText(groupEdit.getText()+"+1",false);parseGroups();};
 divide3.onClick=[this]{subdivision(3);};divide6.onClick=[this]{subdivision(6);};restore.onClick=[this]{subdivision(0);};off.onClick=[this]{if(selectedRow>=0){juce::ScopedLock lock(p.modelLock);auto& l=p.pattern.bars[bar][selectedRow];for(int i=std::min(anchor,endCell);i<=std::max(anchor,endCell);++i)l[i].velocity=0;commit();}};
 variate.onClick=[this]{parseGroups();juce::ScopedLock lock(p.modelLock);int cur=bar;if(p.pattern.barLocked[cur]){status="Bar "+juce::String(cur+1)+" is locked - cannot variate.";repaint();return;}auto backup=p.pattern.bars;p.pattern.seed=juce::Random::getSystemRandom().nextInt(999999999);seedEdit.setText(juce::String(p.pattern.seed),false);bool ok=p.pattern.generate();if(ok){for(int b=0;b<16;++b)if(b!=cur)p.pattern.bars[b]=backup[b];status="Variated bar "+juce::String(cur+1)+". Other 15 bars restored.";}else status="Fix grouping before variating.";clearSelection();commit();};
 copyBar.onClick=[this]{int cur=bar,nxt=bar+1;if(nxt>=16){status="No next bar to copy into (already bar 16).";repaint();return;}juce::ScopedLock lock(p.modelLock);if(p.pattern.barLocked[nxt]){status="Target bar "+juce::String(nxt+1)+" is locked - copy blocked.";repaint();return;}for(int r=0;r<8;++r){if(p.pattern.locked[r])continue;p.pattern.bars[nxt][r]=p.pattern.bars[cur][r];}status="Copied bar "+juce::String(cur+1)+" into bar "+juce::String(nxt+1)+". Locked tracks/bars kept.";commit();};
 exportButton.addMouseListener(&dragListener,false);exportButton.onClick=[this]{status="Drag this button into Studio One, or use SAVE .MID.";repaint();};saveButton.onClick=[this]{auto f=p.exportMidi();if(!f.existsAsFile()){status="MIDI export failed.";return;}chooser=std::make_unique<juce::FileChooser>("Save 16-bar MIDI",juce::File::getSpecialLocation(juce::File::userDocumentsDirectory).getChildFile(f.getFileName()),"*.mid");chooser->launchAsync(juce::FileBrowserComponent::saveMode|juce::FileBrowserComponent::canSelectFiles|juce::FileBrowserComponent::warnAboutOverwriting,[safe=juce::Component::SafePointer<Editor>(this),f](const juce::FileChooser& fc){if(safe!=nullptr){auto dest=fc.getResult();if(dest!=juce::File()){safe->status=f.copyFileTo(dest)?"Saved "+dest.getFileName():"Save failed.";safe->repaint();}}});};
 sync();updateSelection();setSize(1120,760);startTimerHz(25);
 }
 ~Editor()override{stopTimer();exportButton.removeMouseListener(&dragListener);setLookAndFeel(nullptr);}
 void resized()override{play.setBounds(700,30,110,32);tempo.setBounds(530,32,160,27);meter.setBounds(865,114,210,28);numerator.setBounds(865,150,95,25);denominator.setBounds(965,150,110,25);groupEdit.setBounds(865,200,210,28);addGroup.setBounds(965,234,110,23);density.setBounds(865,304,210,26);development.setBounds(865,356,210,26);fill.setBounds(865,408,210,26);space.setBounds(865,460,210,26);ghost.setBounds(865,600,100,22);accent.setBounds(970,600,105,22);seedEdit.setBounds(865,566,150,26);generate.setBounds(865,632,210,34);reroll.setBounds(865,676,210,26);exportButton.setBounds(865,712,128,28);saveButton.setBounds(998,712,77,28);grid16.setBounds(865,512,102,28);grid32.setBounds(973,512,102,28);barLock.setBounds(150,590,118,28);variate.setBounds(274,590,150,28);copyBar.setBounds(430,590,180,28);
 int bx=150,by=104,bw=38,bh=30,gap=3,ggap=9;for(int b=0;b<16;++b){int g=b/4;int x=150+g*(4*bw+3*gap+ggap)+(b%4)*(bw+gap);bars16[b].setBounds(x,by,bw,bh);}
 for(int r=0;r<8;++r)locks[r].setBounds(112,grid.getY()+r*42+10,24,22);
 divide3.setBounds(530,534,58,28);divide6.setBounds(592,534,58,28);restore.setBounds(654,534,68,28);off.setBounds(726,534,58,28);}
 void paint(juce::Graphics& g)override{g.fillAll(juce::Colour(0xfff4f0f8));g.setColour(paper);g.fillRoundedRectangle(20,90,826,650,13);g.fillRoundedRectangle(860,90,240,650,13);text(g,"ozo",{26,24,53,42},29);text(g,"LATTICE",{84,24,225,42},30);text(g,"MATH ROCK DRUM MACHINE",{27,63,350,14},10,muted);text(g,"16 BARS / 8 VOICES - v0.2",{908,36,190,25},11,muted);
 text(g,"TEMPO",{470,32,60,25},10,muted);text(g,"BARS",{38,104,90,30},11,muted);for(int b=0;b<16;++b)bars16[b].setToggleState(b==bar,juce::dontSendNotification);text(g,"BAR "+juce::String(bar+1)+" / 16",{352,172,200,18},11,muted);text(g,"METER",{865,96,210,16},10,muted);text(g,"GROUPING / EIGHTH NOTES",{865,182,210,16},10,muted);text(g,"DENSITY",{865,286,210,16},10,muted);text(g,"DEVELOPMENT",{865,338,210,16},10,muted);text(g,"FILL",{865,390,210,16},10,muted);text(g,"SPACE",{865,442,210,16},10,muted);text(g,"GRID (snap)",{865,494,210,16},10,muted);text(g,"SEED",{865,548,210,16},10,muted);
 juce::ScopedLock lock(p.modelLock);auto& m=p.pattern;const float scale=float(grid.getWidth())/m.barTicks();int start=0;for(int i=0;i<int(m.groups.size());++i){int len=m.groups[i]*240;float x=grid.getX()+start*scale,w=len*scale;if(start+len<=m.barTicks()){g.setColour(juce::Colour(0xffe6ddf0));g.fillRoundedRectangle(x+2,146,w-4,22,4);text(g,juce::String(m.groups[i]),{int(x),146,int(w),22},11,muted,juce::Justification::centred);g.setColour(juce::Colour(0xffd5c8e2));g.drawVerticalLine(int(x),190,526);}start+=len;}
 int gs=m.gridStep>0?m.gridStep:120;g.setColour(juce::Colour(0xffece6f2));for(int t=0;t<=m.barTicks();t+=gs){float x=grid.getX()+t*scale;if(x>grid.getX()&&x<grid.getRight())g.drawVerticalLine(int(x),float(grid.getY()+2),float(grid.getY()+grid.getHeight()-2));}
 text(g,m.valid()?"VALID  /  "+juce::String(m.eighths())+" eighths":"TOTAL MISMATCH",{865,262,210,16},10,m.valid()?juce::Colour(0xff578d75):juce::Colour(0xffc15c73));
 for(int r=0;r<8;++r){int y=grid.getY()+r*42;g.setColour(colours[r]);g.fillRoundedRectangle(37,float(y+15),3,12,1);text(g,lattice::names[r],{48,y,62,42},13);g.setColour(line);g.drawHorizontalLine(y+41,150,840);auto& l=m.bars[bar][r];for(int i=0;i<int(l.size());++i){auto& c=l[i];float x=grid.getX()+c.start*scale,w=c.length*scale;g.setColour(juce::Colour(0xfff3f3f3));g.fillRect(x+1.f,float(y+32),std::max(1.f,w-2),2.f);if(c.start%240==0){g.setColour(line);g.drawVerticalLine(int(x),float(y+4),float(y+38));}if(c.length!=120){g.setColour(colours[r].withAlpha(0.5f));g.fillRect(x+1,float(y+37),std::max(1.f,w-2),1.f);}if(c.velocity){float h=c.velocity==127?27.f:c.velocity==80?20.f:10.f;float nw=std::max(2.f,std::min(14.f,w-5));g.setColour(colours[r].withAlpha(c.velocity==40?0.42f:c.velocity==80?0.77f:1.f));g.fillRoundedRectangle(x+(w-nw)*0.5f,y+34-h,nw,h,2);}if(r==selectedRow&&i>=std::min(anchor,endCell)&&i<=std::max(anchor,endCell)){g.setColour(juce::Colour(0xff8d70b2).withAlpha(0.13f));g.fillRect(x,float(y+2),w,38.f);g.setColour(juce::Colour(0xffac90cc));g.drawRect(x,float(y+2),w,38.f,1.f);}}
 }
 int pt=p.playTick.load();if(pt>=0&&pt/m.barTicks()==bar){g.setColour(juce::Colour(0xff83649f));float x=grid.getX()+(pt%m.barTicks())*scale;g.drawLine(x,187,x,526,1.5);}
 text(g,selectedRow>=0?"SELECTED / "+juce::String(lattice::names[selectedRow]):"VELOCITY",{39,534,260,18},10,muted);text(g,"VELOCITY",{39,560,90,18},10,muted);for(int k=0;k<3;++k){g.setColour(colours[0].withAlpha(k==0?1.f:k==1?0.77f:0.42f));g.fillRoundedRectangle(float(150+k*91),566,8,15,2);text(g,k==0?"127":k==1?"80":"40",{164+k*91,559,55,25},11,muted);}
 text(g,"Click: note on/off   /   Right-click or Shift-click: velocity   /   Drag: select one lane",{28,620,800,18},11,muted);
 text(g,"VARIATE BAR regenerates only this bar (others restored). COPY > NEXT respects bar & track locks.",{28,644,820,18},11,muted);
 text(g,status,{28,668,1060,18},11);}
 void mouseDown(const juce::MouseEvent& ev)override{if(ev.y>=146&&ev.y<168&&ev.x>=grid.getX()&&ev.x<grid.getRight()){juce::ScopedLock lock(p.modelLock);int t=int(double(ev.x-grid.getX())/grid.getWidth()*p.pattern.barTicks());int pos=0;for(size_t i=0;i<p.pattern.groups.size();++i){pos+=p.pattern.groups[i]*240;if(t<pos){if(ev.mods.isRightButtonDown()){p.pattern.groups.erase(p.pattern.groups.begin()+int(i));}else p.pattern.groups[i]=std::clamp(p.pattern.groups[i]+(ev.mods.isShiftDown()?-1:1),1,32);juce::StringArray a;for(int n:p.pattern.groups)a.add(juce::String(n));groupEdit.setText(a.joinIntoString("+"),false);status="Group: click +1 / Shift-click -1 / right-click remove.";commit();return;}}}auto h=snapHit(ev.getPosition());if(h.first<0){clearSelection();return;}selectedRow=h.first;anchor=endCell=h.second;down=ev.getPosition();dragging=false;updateSelection();}
 void mouseDrag(const juce::MouseEvent& ev)override{if(selectedRow<0)return;auto h=hit({std::clamp(ev.x,grid.getX(),grid.getRight()-1),grid.getY()+selectedRow*42+20});if(h.second>=0){endCell=h.second;dragging=ev.getDistanceFromDragStart()>4;updateSelection();}}
 void mouseUp(const juce::MouseEvent& ev)override{if(selectedRow<0||anchor<0)return;if(!dragging){juce::ScopedLock lock(p.modelLock);auto& c=p.pattern.bars[bar][selectedRow][anchor];if(ev.mods.isRightButtonDown()||ev.mods.isShiftDown())c.velocity=c.velocity==127?80:c.velocity==80?40:127;else c.velocity=c.velocity?0:80;commit();}repaint();}
};
}
juce::AudioProcessorEditor* makeLatticeEditor(LatticeProcessor& p){return new Editor(p);}
