#include "Processor.h"
LatticeProcessor::LatticeProcessor():AudioProcessor(BusesProperties().withOutput("Output",juce::AudioChannelSet::stereo(),true)){changed();}
juce::AudioProcessorEditor* LatticeProcessor::createEditor(){return makeLatticeEditor(*this);}
void LatticeProcessor::changed(){juce::ScopedLock model(modelLock);juce::ScopedLock lock(scheduleLock);pending.events.clear();pending.events.reserve(65536);pending.count=0;pending.ticks=pattern.barTicks()*lattice::phraseBars;pending.bpm=pattern.bpm;for(int b=0;b<lattice::phraseBars;++b)for(int r=0;r<lattice::tracks;++r)for(auto c:pattern.bars[b][r])if(c.velocity&&pending.count<int(pending.events.capacity())){pending.events.push_back({b*pattern.barTicks()+c.start,r,c.velocity});++pending.count;}std::sort(pending.events.begin(),pending.events.begin()+pending.count,[](const Event& a,const Event& b){return a.tick<b.tick;});version.fetch_add(1,std::memory_order_release);}
void LatticeProcessor::silence(){for(auto& v:voices){v.amplitude=0;v.age=100;}}
void LatticeProcessor::prepareToPlay(double sr,int){rate=sr;silence();internalTick=0;wasRunning=wasPreview=wasHost=false;applied=0;}
void LatticeProcessor::releaseResources(){silence();playTick.store(-1);}
void LatticeProcessor::trigger(int r,int vel){if(r<0||r>=lattice::tracks)return;if(r==3)for(auto& v:voices)if(v.row==4)v.amplitude=0;Voice* target=&voices[0];for(auto& v:voices)if(v.amplitude==0){target=&v;break;}else if(v.age>target->age)target=&v;*target={r,0,0,0,float(vel)/127.f,0};}
float LatticeProcessor::sample(Voice& v){if(v.amplitude==0)return 0;const double t=v.age;const double duration[8]={0.7,0.48,0.12,0.13,0.75,0.8,1.8,3.5};if(t>duration[v.row]){v.amplitude=0;return 0;}noiseState^=noiseState<<13;noiseState^=noiseState>>17;noiseState^=noiseState<<5;float noise=float(double(noiseState)/2147483648.0-1.0);float high=noise-v.previousNoise;v.previousNoise=noise;double freq=50,decay=10;float out=0;constexpr double tau=6.283185307179586;
 switch(v.row){case 0:freq=48+115*std::exp(-t*48);decay=9;break;case 1:freq=185;decay=22;break;case 2:freq=820;decay=65;break;case 3:freq=6400;decay=58;break;case 4:freq=5700;decay=8;break;case 5:freq=105+70*std::exp(-t*30);decay=7;break;case 6:freq=2450;decay=3.8;break;case 7:freq=7200;decay=1.0;break;}
 v.phase+=tau*freq/rate;if(v.phase>tau)v.phase-=tau;v.phase2+=tau*freq*1.483/rate;if(v.phase2>tau)v.phase2-=tau;
 double env=std::exp(-t*decay)*std::min(1.0,t*2000);
 if(v.row==0)out=float(std::sin(v.phase)*env*0.8+noise*std::exp(-t*220)*0.12);
 if(v.row==1)out=float((std::sin(v.phase)*0.35+high*0.38)*env);
 if(v.row==2)out=float((std::sin(v.phase)+0.45*std::sin(v.phase2))*env*0.36);
 if(v.row==3||v.row==4)out=float((high*0.23+std::sin(v.phase)*std::sin(v.phase2)*0.1)*env);
 if(v.row==5)out=float((std::sin(v.phase)+0.13*std::sin(v.phase2))*env*0.6);
 if(v.row==6)out=float((std::sin(v.phase)*std::sin(v.phase2)*0.25+high*0.1)*env);
 if(v.row==7)out=float((high*0.45+noise*std::exp(-t*8)*0.22+(std::sin(v.phase)*0.5+std::sin(v.phase2)*0.3))*env);
 v.age+=1.0/rate;return out*v.amplitude;}
void LatticeProcessor::processBlock(juce::AudioBuffer<float>& audio,juce::MidiBuffer& midi){juce::ScopedNoDenormals no;audio.clear();auto ver=version.load(std::memory_order_acquire);if(ver!=applied){juce::ScopedTryLock lock(scheduleLock);if(lock.isLocked()){active=pending;applied=ver;}}
 bool hostPlaying=false;double hostTick=0,hostBpm=0;bool hasHost=false;double bpm=active.bpm;
 if(auto* ph=getPlayHead())if(auto pos=ph->getPosition()){if(auto b=pos->getBpm())if(std::isfinite(*b)&&*b>0)hostBpm=std::clamp(*b,1.0,999.0);if(auto q=pos->getPpqPosition()){if(std::isfinite(*q)){hostTick=*q*480.0;hasHost=true;hostPlaying=pos->getIsPlaying();}}}
 const bool local=preview.load();const bool useHost=hasHost&&hostPlaying&&!local;if(useHost&&hostBpm>0)bpm=hostBpm;
 bool running=local||useHost;double step=bpm*480.0/(60.0*rate);displayedBpm.store(bpm);if(local&&!wasPreview)internalTick=0;if(!running&&wasRunning)silence();if(useHost&&wasHost&&std::abs(hostTick-expectedHostTick)>step*2)silence();if(useHost!=wasHost&&running)silence();double tick=useHost?hostTick:internalTick;
 auto it=midi.cbegin();auto finish=midi.cend();for(int i=0;i<audio.getNumSamples();++i){while(it!=finish&&(*it).samplePosition<=i){auto msg=(*it).getMessage();if(msg.isNoteOn()){for(int r=0;r<lattice::tracks;++r)if(msg.getNoteNumber()==lattice::notes[r])trigger(r,msg.getVelocity());}else if(msg.isAllNotesOff()||msg.isAllSoundOff())silence();++it;}
 if(running&&active.ticks>0){double wrapped=std::fmod(tick,active.ticks);if(wrapped<0)wrapped+=active.ticks;auto fire=[&](double a,double z){auto begin=active.events.begin(),end=begin+active.count;auto e=std::lower_bound(begin,end,a-0.000001,[](const Event& event,double value){return event.tick<value;});for(;e!=end&&e->tick<z-0.000001;++e)trigger(e->row,e->velocity);};fire(wrapped,std::min(wrapped+step,double(active.ticks)));if(wrapped+step>active.ticks)fire(0,wrapped+step-active.ticks);tick+=step;}
 float l=0,r=0;for(auto& voice:voices){float s=sample(voice);const float pan[8]={0,0,-0.15f,-0.25f,-0.2f,0.2f,0.3f,0.1f};l+=s*(1.f-pan[voice.row])*0.65f;r+=s*(1.f+pan[voice.row])*0.65f;}if(audio.getNumChannels()>0)audio.setSample(0,i,std::tanh(l));if(audio.getNumChannels()>1)audio.setSample(1,i,std::tanh(r));}
 if(local)internalTick=tick;expectedHostTick=hostTick+audio.getNumSamples()*step;wasHost=useHost;wasPreview=local;wasRunning=running;playTick.store(running?int(std::fmod(std::max(0.0,tick),double(active.ticks))):-1);midi.clear();}
juce::File LatticeProcessor::exportMidi(){lattice::Pattern m;{juce::ScopedLock lock(modelLock);m=pattern;}juce::MidiMessageSequence seq;auto tempo=juce::MidiMessage::tempoMetaEvent(int(60000000.0/m.bpm));seq.addEvent(tempo);seq.addEvent(juce::MidiMessage::timeSignatureMetaEvent(m.numerator,m.denominator));for(int b=0;b<lattice::phraseBars;++b)for(int r=0;r<lattice::tracks;++r)for(auto c:m.bars[b][r])if(c.velocity){auto on=juce::MidiMessage::noteOn(10,lattice::notes[r],juce::uint8(c.velocity));on.setTimeStamp(b*m.barTicks()+c.start);seq.addEvent(on);auto off=juce::MidiMessage::noteOff(10,lattice::notes[r]);off.setTimeStamp(b*m.barTicks()+c.start+std::max(1,std::min(60,c.length-1)));seq.addEvent(off);}auto end=juce::MidiMessage::endOfTrack();end.setTimeStamp(m.barTicks()*lattice::phraseBars);seq.addEvent(end);seq.updateMatchedPairs();juce::MidiFile file;file.setTicksPerQuarterNote(480);file.addTrack(seq);juce::StringArray groups;for(int n:m.groups)groups.add(juce::String(n));auto folder=juce::File::getSpecialLocation(juce::File::tempDirectory).getChildFile("ozo-LATTICE");if(!folder.createDirectory())return {};auto f=folder.getChildFile("LATTICE_"+juce::String(m.numerator)+"-"+juce::String(m.denominator)+"_"+groups.joinIntoString("+")+"_"+juce::String(m.bpm,0)+"bpm_"+juce::Uuid().toString().substring(0,8)+".mid");juce::FileOutputStream stream(f);if(!stream.openedOk()||!file.writeTo(stream))return {};stream.flush();return f;}
void LatticeProcessor::getStateInformation(juce::MemoryBlock& dest){juce::ScopedLock lock(modelLock);juce::XmlElement xml("LATTICE");xml.setAttribute("version",2);xml.setAttribute("n",pattern.numerator);xml.setAttribute("d",pattern.denominator);xml.setAttribute("bpm",pattern.bpm);xml.setAttribute("seed",pattern.seed);xml.setAttribute("density",double(pattern.density));xml.setAttribute("ghost",pattern.ghost);xml.setAttribute("accents",pattern.accents);xml.setAttribute("development",double(pattern.development));xml.setAttribute("fill",double(pattern.fill));xml.setAttribute("space",double(pattern.space));xml.setAttribute("gridStep",pattern.gridStep);juce::StringArray gs;for(auto n:pattern.groups)gs.add(juce::String(n));xml.setAttribute("groups",gs.joinIntoString("+"));juce::StringArray bl;for(bool b:pattern.barLocked)bl.add(juce::String(b?1:0));xml.setAttribute("barlock",bl.joinIntoString(","));for(int b=0;b<lattice::phraseBars;++b)for(int r=0;r<lattice::tracks;++r){auto* lane=xml.createNewChildElement("lane");lane->setAttribute("b",b);lane->setAttribute("r",r);lane->setAttribute("lock",pattern.locked[r]);for(auto c:pattern.bars[b][r]){auto* x=lane->createNewChildElement("c");x->setAttribute("t",c.start);x->setAttribute("l",c.length);x->setAttribute("v",c.velocity);}}copyXmlToBinary(xml,dest);}
void LatticeProcessor::setStateInformation(const void* data,int size){if(size<=0||size>8000000)return;auto xml=getXmlFromBinary(data,size);if(!xml||!xml->hasTagName("LATTICE"))return;int version=xml->getIntAttribute("version",1);if(version!=1&&version!=2)return;lattice::Pattern m;int n=xml->getIntAttribute("n"),d=xml->getIntAttribute("d");if(n<1||n>16||(d!=4&&d!=8))return;m.meter(n,d);m.bpm=xml->getDoubleAttribute("bpm",100);m.seed=xml->getIntAttribute("seed",1729);m.density=float(xml->getDoubleAttribute("density",.55));m.ghost=xml->getBoolAttribute("ghost",true);m.accents=xml->getBoolAttribute("accents",true);if(!std::isfinite(m.bpm)||m.bpm<40||m.bpm>240||!std::isfinite(m.density)||m.density<0||m.density>1)return;m.groups.clear();auto gs=juce::StringArray::fromTokens(xml->getStringAttribute("groups"),"+","");if(gs.size()>32)return;for(auto s:gs){if(!s.containsOnly("0123456789")||s.length()>2||s.getIntValue()<1||s.getIntValue()>32)return;m.groups.push_back(s.getIntValue());}if(!m.valid())return;
 if(version>=2){m.development=float(xml->getDoubleAttribute("development",0));m.fill=float(xml->getDoubleAttribute("fill",0));m.space=float(xml->getDoubleAttribute("space",0));if(!std::isfinite(m.development)||m.development<0||m.development>1)return;if(!std::isfinite(m.fill)||m.fill<0||m.fill>1)return;if(!std::isfinite(m.space)||m.space<0||m.space>1)return;int g=xml->getIntAttribute("gridStep",60);if(g!=60&&g!=120)return;m.gridStep=g;auto bl=juce::StringArray::fromTokens(xml->getStringAttribute("barlock"),",","");if(bl.size()>lattice::phraseBars)return;for(int b=0;b<(int)bl.size()&&b<lattice::phraseBars;++b)m.barLocked[b]=bl[b].getIntValue()!=0;}
 else{m.gridStep=120;}
 int barsN=version>=2?lattice::phraseBars:4;int trkN=version>=2?lattice::tracks:7;std::vector<std::vector<bool>> seen(barsN,std::vector<bool>(trkN,false));
 for(auto* lane:xml->getChildIterator()){int b=lane->getIntAttribute("b",-1),r=lane->getIntAttribute("r",-1);if(!lane->hasTagName("lane")||b<0||b>=barsN||r<0||r>=trkN||seen[b][r])return;seen[b][r]=true;if(r<trkN)m.locked[r]=lane->getBoolAttribute("lock");auto& l=m.bars[b][r];l.clear();int pos=0;for(auto* c:lane->getChildIterator()){int t=c->getIntAttribute("t",-1),len=c->getIntAttribute("l",0),v=c->getIntAttribute("v",-1);if(!c->hasTagName("c")||t!=pos||len<1||len>m.barTicks()-pos||(v!=0&&v!=40&&v!=80&&v!=127)||l.size()>=512)return;l.push_back({t,len,v});pos+=len;}if(pos!=m.barTicks())return;}
 for(auto& row:seen)for(bool s:row)if(!s)return;{juce::ScopedLock lock(modelLock);pattern=std::move(m);}changed();}
juce::AudioProcessor* JUCE_CALLTYPE createPluginFilter(){return new LatticeProcessor();}
